name: Auto approve
on: 
  pull_request:
    branches:
      - master

jobs:
  approve:
    runs-on: ubuntu-latest
    if: github.actor == 'nick' && startsWith(github.head_ref, 'pr_tst')
    steps:
      - uses: hmarr/auto-approve-action@v2.0.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
