name: Test approve
on: 
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Approve PR
        uses: hmarr/auto-approve-action@v2.0.0
        if: github.actor == 'nick'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
