name: Origin Tests

on: push

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Yarn Install
        run: yarn
      - name: Zip workspace
        run: tar -zc --exclude='.git' -f /tmp/workspace.tar.gz .
      - name: Upload Cache
        uses: actions/upload-artifact@master
        with:
          name: workspace
          path: /tmp/workspace.tar.gz

  puppeteer-1:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
      - name: Download Cache
        uses: actions/download-artifact@master
        with:
          name: workspace
          path: /tmp
      - name: Unzip
        run: tar -xzf /tmp/workspace.tar.gz .
      - name: find
        run: find . -maxdepth 2
